### ISSUE TITLE
Resolve package vulnerability (Regular Expression Denial of Service)

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#112]
## Description:
- Due to dependency on inversify-restify-utils on an old version of restify.  Waiting on [this issue](https://github.com/Azure/azure-sdk-for-js/issues/7079) to be resolved
- Vulnerability details:  https://www.npmjs.com/advisories/1171
- Described in README: https://github.com/retaildevcrews/helium-typescript#dependency-vulnerability

**Comment by tobiaswright** [comment]
@aflinchb has someone tried this? https://www.npmjs.com/policies/disputes
