### ISSUE TITLE
Resolve dependency warnings in Docker build

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#113]
## Description:
- Described in Readme: https://github.com/retaildevcrews/helium-typescript#warnings

- [x] npm WARN deprecated @opentelemetry/types@0.2.0: Package renamed to @opentelemetry/api
    - See [tracking issue](https://github.com/Azure/azure-sdk-for-js/issues/7079), [description](https://github.com/open-telemetry/opentelemetry-js)
- [x] npm WARN deprecated request@2.88.2: request has been deprecated
    - See [jsdom tracking issue](https://github.com/jsdom/jsdom/issues/2792) and [adal tracking issue](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/229), [description](https://github.com/request/request/issues/3142)
- [x] npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
    - See [tracking issue](https://github.com/node-gfx/node-canvas-prebuilt/pull/80)

The original warnings (above) are all resolved and removed from the readme. The remaining are: 
- [ ] npm WARN gulp-debug@4.0.0 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.
    - Still needs investigation as to what the impact is here - so far, it has had no impact on app performance/functionality
- [x] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
    - after initial research, this warning is optional and does not affect the app so no further action is needed
- [x] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    - after initial research, this warning is optional and does not affect the app so no further action is needed

**Comment by tobiaswright** [comment]
I've done some research on the issue, and appears there is no way around having to add gulp to the package.json.

I've installed gulp and it does generate two new warning, similar to the warning that are being generated now. The screenshot below is the new warning that are generated.

![Screenshot from 2020-05-01 11-51-22](https://user-images.githubusercontent.com/759066/80819529-21219300-8ba3-11ea-92a7-100825eb5e62.png)

This is current warning for reference:

![Screenshot from 2020-05-01 11-52-07](https://user-images.githubusercontent.com/759066/80819601-3c8c9e00-8ba3-11ea-96ed-041f937a0b7a.png)

I narrowed the package that is causing that issue. It's [inversify-restify-utils](https://github.com/inversify/inversify-restify-utils) - I believe there that the [this module](https://github.com/inversify/inversify-restify-utils/blob/b305a368b11335efa5116064926574ac0ee6f46c/package.json#L61) should be in developer dependencies.

I can't recall if this the module with the absentee owner.

At any rate installing gulp does not appear to have any adverse on the app, and it has passed webvalidate test

**Comment by tobiaswright** [comment]
The other thing we may want to consider is turning adjusting the log level for npm - https://docs.npmjs.com/misc/config

**Comment by tobiaswright** [comment]
Oh, also, we wouldn’t see the other two warnings on a Mac: https://stackoverflow.com/questions/27686889/npm-install-warn-on-dependency

**Comment by tobiaswright** [comment]
So adding gulp does add a low severity vulnerability, it will not be fixed in the current version of gulp: https://github.com/gulpjs/gulp-cli/issues/207
