### ISSUE TITLE
Investigate/fix sherbert's worsening performance

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#120]
## Description
- Sherbert's server response time slowed down significantly after the Cosmos DB collection was updated to be provisioned for 400 RU's (usually 1k+).  Even after correcting the throughput provisioning, the app continued to have a slow performance and potentially showed signs of a memory leak.

## Expected Behavior
- Response time should be around 20s when the underlying Cosmos DB collection is provisioned to 1k RU throughput. 

## Reproduce
1. Deploy helium-typescript to Sherbert  (make sure webv is sending requests)
2.  Provision Cosmos DB throughput to 400
3.  Observe memory usage growth and increased response time of Sherbert.
[NOTE: Repro steps are not unique to the issue, the perf takes a bad hit regardless of provisioning of RU's]

## Additional Context
- I looked through the logs and the main thing I noticed was a very large error message when the 429 cosmos error is thrown: 
![image](https://user-images.githubusercontent.com/3301452/77465522-c001e500-6dd6-11ea-9d99-d74ed6e5e119.png)

- One theory is the memory leak is related to the large error message and potenially not completely/appropriately handling the 429 error (and other 4xx) in our data service and controllers. 

- Another theory is that this is not necessarily a memory leak (the app isn't crashing, and there are no signs of this in the App Service Plan memory usage metrics like before), but somehow related to the change of using the composite index in Cosmos DB. Both sherbert and bluebell have had strange performance patterns after the change.

**Comment by codefoster** [comment]
Used a couple of different profilers to attempt to see how the app itself is using memory. No leads so far.
