### ISSUE TITLE
Enforce serialization order for JSON results (match C#)

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#13]
After removing the create/update/delete functionality, the actor and movie models are not actually being used anymore as implemented today. We need to decide what to do, if there's a way to use them in the results to specify the order that fields get serialized to make the JSON more readable and match C#'s ordering.

**Comment by bartr** [comment]
As long as the json parses via the shared integration test, we've met the goal we agreed on.

We don't need to match the C# ordering exactly, but I think having the json be "more human readable" is a goal that fits with "developer experience".

We also have the goal of "idiomatic" to the language. If we can remain idiomatic and make it more human readable, I think it's worth doing.

**Comment by aflinchb** [comment]
Got it - I am good with not requiring to match the ordering exactly as the integration test passes and the json is just as readable (in my opinion).  

On this same topic however, I noticed an inconsistency with what fields are returned for node vs. C# -- deathYear is only returned if it has a value in the document, where as in C# it defaults to 0.  I'd have to do some research into how to implement this in node if we want them to have the same behavior there.

**Comment by aflinchb** [comment]
Resolved in Design Review Meeting:

- Not requiring to match the order
- deathYear should not be returned if it does not exist, this was a bug on C# : https://github.com/retaildevcrews/helium-csharp/issues/25
