### ISSUE TITLE
Update logging to "match" C#

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#14]
## Description:
- Consider adding a warn/warning level of logging to the bunyan logging.
- Investigate how to control logging levels by "mode" (i.e. dev vs. production - only log "trace" in dev)

**Comment by codefoster** [comment]
On a related note. I looked at Bunyan and it looks like a good logging library in my assessment. I suggest we stick with it.

**Comment by tobiaswright** [comment]
Hi @aflinchb I'd like to pick this up. I want to learn a little more about Bunyan, and maybe we can put our heads together in a day or two to discuss?

**Comment by tobiaswright** [comment]
@aflinchb are there any flags that are set that denote prod vs dev?
