### ISSUE TITLE
Update Swagger documentation to match C#

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#15]
## Description:
Mostly phrasing and cosmetic changes needed.
For reference: https://bluebell.azurewebsites.net/index.html

Note: this task should be done after C# is updated to standard. 

## Done Checklist:
_[Remove items that are not required for task]_
- [ ] Code changes reviewed & signed off
- [ ] Code changes checked into master
- [ ] CI completes successfully
- [ ] CD completes successfully

**Comment by bartr** [comment]
- Should test to see if type script can use the same swagger.json file as C# so we can edit in one location
- would need to deal with /healthz/dotnet not being present in other languages
  - could just remove from swagger.json for simplicity
