### ISSUE TITLE
Improve/add exception handling as needed

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#16]
## Description:
- Look through app and fix exception handling as needed
- Remove response when 404 error is returned when reading a single document.  Currently, when you try to read a single movie/actor by id, the error message is returned.  Expected behavior is no response (basically remove line "result = err.toString()" from movie.ts and actor.ts controllers. 

## Done Checklist:
- [ ] Code changes reviewed & signed off
- [ ] Code changes checked into master
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [ ] CI completes successfully 
- [ ] CD completes successfully

**Comment by tobiaswright** [comment]
Overall, the error catching looks fine. The only thing we might want to consider at some point is to consolidate error handling to ensure that messaging is similar and to keep track of errors. I did a little research on different patterns, but haven't found anything, but it may be worth putting a task in the backlog for it.
