### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#2]
Currently, there is a placeholder script that will run unit tests using the mocha framework.  Part of this task is to decide if mocha is the right framework to use. 

## Description:
_[Add description of the task]_

## Done Checklist:
_[Remove items that are not required for task]_
- [ ] Code changes reviewed & signed off
- [x] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Code changes checked into master
- [x] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [x] CI completes successfully
- [x] CD completes successfully
- [ ] New changes in smoke test for 48hrs

**Comment by aflinchb** [comment]
After a bit of research, I am not seeing a good pattern for mocking the database in node/typescript (i.e. from local json files) for testing out the controller.  I am guessing this is why the initial implementation used mocha+chai to test on the actual database.  

Adding Question label to discuss if others are aware of better ways to implement the unit tests (without actually having a dependency on a Cosmos DB database), or if we want to implement "integration testing" in this repo in addition to using the integration test in rdc/helium

**Comment by aflinchb** [comment]
Moving to backlog until SMKer can review

**Comment by atxryan** [comment]
@aflinchb We can also look at switching out to use Jest. I used it at OneWeek for a TypeScript serverless project. https://jestjs.io/docs/en/mock-functions#mock-implementations
