### ISSUE TITLE
TypeScript Docker environment for users that can't meet current Helium requirements.

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/helium-typescript#212]
## Description:

Give users a Docker environment for setting up Helium. Some users can't meet the current requirements, but they are able to use Docker Desktop.

- [ ] A Dockerfile for helium typescript that can be used locally and in codespaces. This should include all the tools needed to step through the Helium setup.
- [ ] Build the Dockerfile as part of ci/cd. Build on changes to the file, build and push to Docker Hub when merging to main.
- [ ] Build and push the Dockerfile on a recurring schedule for package updates.
- [ ] For codespaces, use the pre-built images for faster startup.

- References https://github.com/retaildevcrews/helium/issues/579

**Comment by dsturgell** [comment]
Team agreed to 'Close' issue; developer would need to ensure they have proper permissions on laptop to implement or could leverage codespaces.
