### ISSUE TITLE
Implement idiomatic health check endpoint

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#23]
Will review with SMKer to see if there is an idiomatic response for Node.js+typescript apps. 
## Description:
_[Add description of the task]_

## Done Checklist:
_[Remove items that are not required for task]_
- [ ] Code changes reviewed & signed off
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Code changes checked into master
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] New changes in smoke test for 48hrs

**Comment by bartr** [comment]
We were not able to find anything for Node similar to the dotnet health check, so closing as n/a
