### ISSUE TITLE
Investigate other/additional linting options

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#57]
## Description:
- helium-typescript currently uses tslint as a linter
- This task covers investigating other or additional options that should be included to help code quality and looking at the existing linting options enforced to make sure it is a complete/reasonable list (i.e. nothing important is excluded).

**Comment by codefoster** [comment]
I finished working with Jason LaChance's dev crew on the Starbucks project using Node and TypeScript and they had eslint-typescript in use, so I can use that as a reference and migrate this project to that. eslint-typescript is the clear choice for linting.

**Comment by codefoster** [comment]
I'll close this and create a task to implement eslint-typescript.
