### ISSUE TITLE
Add unit tests for query logic

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#58]
## Description:
- Investigate best way to mock controllers and database contents
- References #45

**Comment by tobiaswright** [comment]
Making some progress. Initially went down the path of creating folders called __mocks__, but  there is not a lot of clarity of how to mock classes, and more importantly, how to handle instances of classes that are invoking instances of other classes. At any rate there is a way to mock the inputs, but need to work on testing the outputs. and getting as much coverage of the class methods as possible as some have a lot cases that should be included in the test. This issue will need to carry over to the next sprint,

**Comment by tobiaswright** [comment]
Got past the blockers, and coverage is probably around 80%. Should be submitting a PR this evening. There is one method that can not be tested as there is a private variable being set and unable to access the function. We should probably update it and make it closer to a pure function.
