### ISSUE TITLE
Add support for AKS pod identity

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#6]
## Description:
- Make needed updates to helium-typescript to support pod identity and running on AKS

## Done Checklist:
_[Remove items that are not required for task]_
- [ ] Code changes reviewed & signed off
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Code changes checked into master
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] New changes in smoke test for 48hrs

**Comment by evillgenius75** [comment]
@aflinchb I am currently getting this error from the container running typescript
```
No authentication type specified, defaulting to MSI.
{"name":"bunyanLog","hostname":"helium-ts-84cf54b568-pb92w","pid":18,"level":50,"err":{},"corr_id":"10616dab-2735-4815-9e60-f7b681d6ced4","msg":"Failed to get required Cosmos DB secrets from KeyVault","time":"2020-03-12T18:27:52.301Z","v":0}
{"name":"bunyanLog","hostname":"helium-ts-84cf54b568-pb92w","pid":18,"level":50,"err":{},"corr_id":"10616dab-2735-4815-9e60-f7b681d6ced4","msg":"Failed to get required Cosmos DB secrets from KeyVault","time":"2020-03-12T18:27:52.301Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helium@0.0.6 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helium@0.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appuser/.npm/_logs/2020-03-12T18_27_52_309Z-debug.log
```

This cluster is running csharp with the same setup and no issues, so it has to be in the keyvault provider for node that may have an issue
