### ISSUE TITLE
Research/review logging package and granularity

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#88]
## Description:
- Research logging package (bunyan) and granularity (trace and log) in helium-typescript
- Goal is to make sure bunyan is the appropriate logging package to use (or determine a better approach)
- Currently, only trace and log levels of logging are used, and there is no way to configure what is output (i.e. in debug/dev mode vs. production).  This may be OK, but want to review. 

- References #11

**Comment by codefoster** [comment]
I looked into Bunyan. I have never used it. It looks like a great choice, and I see no reason to change unless there are some pain points or missing features.
