### ISSUE TITLE
Review Cosmos DB data provider

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#91]
## Description:
- Make sure the CosmosDB data provider in helium-typescript seems to be a sufficient data layer abstraction
- References #11

**Comment by aflinchb** [comment]
@codefoster --  can we consider this task complete/closed? You've made some great suggestions and changes for refactoring all up that have touched on the data service. 

Since this is your last week (😢) I wanted to make sure there wasn't general feedback here we can take forward.

**Comment by codefoster** [comment]
Not quite yet. I've been meaning to look at the CosmosDBService itself, and still think I'll get to that this week.

**Comment by codefoster** [comment]
Adding this here for posterity...

> Tobias, I started looking at the CosmosDBService module today to see if I could suggest any optimizations. I found some, but instead of following through with a PR, I think it makes more sense to leave it alone since you'll be refactoring the CosmosDBService to use parameterized queries. So you can just reference my codefoster/cosmosdbservice branch. Here's a summary of the changes I made...
> - refactored the defaulting and range validation of the page size and number since it was in common between the actors and movies queries. I added the conditionPages function.
> - used JavaScript template literals for the SQL strings to make it more readable. For instance, sql += " and contains(m.textSearch, '" + actorName + "')"; became sql += ` and contains(m.textSearch, '${actorName}')"
> - removed the braces from some if statements to make the query composition more readible. I realize that some people don't agree with this code formatting. I use it more often than most. It seemed like enough of an advantage in this case. Your call.
