### ISSUE TITLE
Get actors and get actor by id queries return "type" in the movies array (it shouldn't)

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#94]
## Description
- /api/actors/{actorId} and /api/actors both return type in the resulting document's movies array.

Example: 
![image](https://user-images.githubusercontent.com/3301452/76237479-555c8100-61fc-11ea-8ad3-dd2b7699a34a.png)

## Expected Behavior
- It should not include the type field in the movies array (example from bluebell below)
![image](https://user-images.githubusercontent.com/3301452/76237607-889f1000-61fc-11ea-84e2-65978860f9e8.png)

**Comment by tobiaswright** [comment]
@aflinchb the movies array is pulled from the db, should be looking at the sql query?

**Comment by aflinchb** [comment]
> @aflinchb the movies array is pulled from the db, should be looking at the sql query?

We can try a similar solution to csharp -- it has a separate "ActorMovie" class: https://github.com/retaildevcrews/helium-csharp/blob/master/src/app/Model/Actor.cs

**Comment by aflinchb** [comment]
Closing per stand up discussion -- this will be fixed with https://github.com/retaildevcrews/imdb/issues/31
